// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocksdb.proto

package com.wxm.rocksdb;

public interface RocksdbActionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RocksdbActionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string info = 2;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>string data = 3;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
