// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocksdb.proto

package com.wxm.rocksdb;

public interface RocksdbRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RocksdbRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table = 1;</code>
   */
  java.lang.String getTable();
  /**
   * <code>string table = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
