// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocksdb.proto

package com.wxm.rocksdb;

public interface RocksdbActionKVSReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RocksdbActionKVSReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string info = 2;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>map&lt;string, string&gt; kvs = 3;</code>
   */
  int getKvsCount();
  /**
   * <code>map&lt;string, string&gt; kvs = 3;</code>
   */
  boolean containsKvs(
      java.lang.String key);
  /**
   * Use {@link #getKvsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getKvs();
  /**
   * <code>map&lt;string, string&gt; kvs = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getKvsMap();
  /**
   * <code>map&lt;string, string&gt; kvs = 3;</code>
   */

  java.lang.String getKvsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; kvs = 3;</code>
   */

  java.lang.String getKvsOrThrow(
      java.lang.String key);
}
