// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocksdb.proto

package com.wxm.rocksdb;

public final class RocksdbProto {
  private RocksdbProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RocksdbRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RocksdbRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RocksdbRequests_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RocksdbRequests_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RocksdbActionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RocksdbActionReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RocksdbActionKVSReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RocksdbActionKVSReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RocksdbActionKVSReply_KvsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RocksdbActionKVSReply_KvsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrocksdb.proto\";\n\016RocksdbRequest\022\r\n\005tab" +
      "le\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\r\n\005value\030\003 \001(\t\">\n\017" +
      "RocksdbRequests\022\r\n\005table\030\001 \001(\t\022\014\n\004keys\030\002" +
      " \003(\t\022\016\n\006values\030\003 \003(\t\">\n\022RocksdbActionRep" +
      "ly\022\014\n\004code\030\001 \001(\005\022\014\n\004info\030\002 \001(\t\022\014\n\004data\030\003" +
      " \001(\t\"\215\001\n\025RocksdbActionKVSReply\022\014\n\004code\030\001" +
      " \001(\005\022\014\n\004info\030\002 \001(\t\022,\n\003kvs\030\003 \003(\0132\037.Rocksd" +
      "bActionKVSReply.KvsEntry\032*\n\010KvsEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012\316\002\n\rRocksdb" +
      "Action\0220\n\006saveKV\022\017.RocksdbRequest\032\023.Rock" +
      "sdbActionReply\"\000\0222\n\007saveKVS\022\020.RocksdbReq" +
      "uests\032\023.RocksdbActionReply\"\000\0223\n\tdeleteKe" +
      "y\022\017.RocksdbRequest\032\023.RocksdbActionReply\"" +
      "\000\0225\n\ndeleteKeys\022\020.RocksdbRequests\032\023.Rock" +
      "sdbActionReply\"\000\0222\n\010getValue\022\017.RocksdbRe" +
      "quest\032\023.RocksdbActionReply\"\000\0227\n\tgetValue" +
      "s\022\020.RocksdbRequests\032\026.RocksdbActionKVSRe" +
      "ply\"\000B!\n\017com.wxm.rocksdbB\014RocksdbProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RocksdbRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RocksdbRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RocksdbRequest_descriptor,
        new java.lang.String[] { "Table", "Key", "Value", });
    internal_static_RocksdbRequests_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RocksdbRequests_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RocksdbRequests_descriptor,
        new java.lang.String[] { "Table", "Keys", "Values", });
    internal_static_RocksdbActionReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RocksdbActionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RocksdbActionReply_descriptor,
        new java.lang.String[] { "Code", "Info", "Data", });
    internal_static_RocksdbActionKVSReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RocksdbActionKVSReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RocksdbActionKVSReply_descriptor,
        new java.lang.String[] { "Code", "Info", "Kvs", });
    internal_static_RocksdbActionKVSReply_KvsEntry_descriptor =
      internal_static_RocksdbActionKVSReply_descriptor.getNestedTypes().get(0);
    internal_static_RocksdbActionKVSReply_KvsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RocksdbActionKVSReply_KvsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
