// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocksdb.proto

package com.wxm.rocksdb;

public interface RocksdbRequestsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RocksdbRequests)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table = 1;</code>
   */
  java.lang.String getTable();
  /**
   * <code>string table = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>repeated string keys = 2;</code>
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <code>repeated string keys = 2;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 2;</code>
   */
  java.lang.String getKeys(int index);
  /**
   * <code>repeated string keys = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);

  /**
   * <code>repeated string values = 3;</code>
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <code>repeated string values = 3;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated string values = 3;</code>
   */
  java.lang.String getValues(int index);
  /**
   * <code>repeated string values = 3;</code>
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);
}
